/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.views;

import com.project.dao.HoaDonChiTietDAO;
import com.project.entity.HangHoaTrongHoaDon;
import com.project.entity.HoaDonChiTiet;
import com.project.utils.AuthenicatedHelper;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vt1
 */
public class ChiTietHDDialog extends javax.swing.JDialog {

    HoaDonChiTietDAO hDCTDAO = new HoaDonChiTietDAO();
    List< HoaDonChiTiet> listhDCT = new ArrayList<>();

    /**
     * Creates new form ChiTietHĐialog
     */
    public ChiTietHDDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xem chi tiết hóa đơn");

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonChiTiet.setRowHeight(23);
        tblHoaDonChiTiet.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(tblHoaDonChiTiet);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Mã Hóa Đơn: ");
        jPanel1.add(jLabel1);

        lblMaHoaDon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaHoaDon.setForeground(new java.awt.Color(255, 0, 0));
        lblMaHoaDon.setText("HD0001");
        jPanel1.add(lblMaHoaDon);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChiTietHDDialog dialog = new ChiTietHDDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    // End of variables declaration//GEN-END:variables
   public void fillTable() {
      
        listhDCT = hDCTDAO.getListHoaDonChiTietByMaHoaDon(AuthenicatedHelper.maHoaDon);
        lblMaHoaDon.setText(AuthenicatedHelper.maHoaDon);
        this.fillDataToTable(listhDCT);
    }

    public void fillDataToTable(List<HoaDonChiTiet> list) {
        DefaultTableModel model = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet hdct : listhDCT) {
            Object[] rows = {
                hdct.getHangHoaTrongHoaDon().getHangHoa().getMaMatHang(),
                hdct.getHangHoaTrongHoaDon().getHangHoa().getTenMatHang(),
                hdct.getHangHoaTrongHoaDon().getSoLuong(),
                hdct.getHangHoaTrongHoaDon().getHangHoa().getDonGia(),
                hdct.getHangHoaTrongHoaDon().getSoLuong() * hdct.getHangHoaTrongHoaDon().getHangHoa().getDonGia()
            };
            model.addRow(rows);
        }
    }
}
